version: 2
mergeable:
  # Auto-request reviews when PR is opened
  - when: pull_request.opened
    validate:
      - do: dependent
        changed:
          file: '*'
    pass:
      - do: request_review
        team_reviewers: ['org/Developers']

  # Approval requirements for regular PRs (not develop→main)
  - when: pull_request.*, pull_request_review.*, pull_request.synchronize
    validate:
      - do: approvals
        min:
          count: 1
          message: "You need at least one approval to merge this PR"
        block:
          changes_requested: true
          message: "The PR contains change requests that needs to be resolved before merge"
        limit:
          teams: ['org/Developers']

  # Auto-pass rule specifically for develop→main PRs
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include:
          regex: '.*'
          message: "develop→main PRs are auto-approved"
    pass:
      - do: comment
        payload:
          body: "🚀 Auto-approved: develop → main release PR"
    filter:
      - do: repository
        base: 'main'
        head: 'develop'

  # Stale PR Management
  - when: schedule.repository
    validate:
      - do: stale
        days: 30
        type: 'pull_request'
        ignore_drafts: true
    pass:
      - do: comment
        payload:
          body: |
            🗑️ This PR has been inactive for 30 days and will be automatically closed.
            
            If you still need this PR:
            - Add a comment to keep it active
            - Update the PR with new commits
            - Convert to draft if still work in progress
      - do: labels
        add: ['stale', 'auto-close-pending']
  
  - when: schedule.repository
    validate:
      - do: stale
        days: 35
        type: 'pull_request'
        ignore_drafts: true
    pass:
      - do: close
        message: "🔒 Auto-closed due to 35 days of inactivity. Feel free to reopen if needed."
